FROM node:22-bookworm-slim AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY
ARG VITE_AUTH_REDIRECT_URL
ARG VITE_SUPABASE_EMAIL_OTP_ENABLED=false
ARG VITE_SUPABASE_APPLE_OAUTH_ENABLED=false
ARG VITE_SUPABASE_ENTERPRISE_SSO_ENABLED=true
ARG VITE_SUPABASE_PASSKEYS_ENABLED=false
ARG VITE_SUPABASE_TOTP_MFA_ENABLED=true
ARG VITE_SUPABASE_SMS_MFA_FALLBACK_ENABLED=false

ENV VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
ENV VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
ENV VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
ENV VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY}
ENV VITE_AUTH_REDIRECT_URL=${VITE_AUTH_REDIRECT_URL}
ENV VITE_SUPABASE_EMAIL_OTP_ENABLED=${VITE_SUPABASE_EMAIL_OTP_ENABLED}
ENV VITE_SUPABASE_APPLE_OAUTH_ENABLED=${VITE_SUPABASE_APPLE_OAUTH_ENABLED}
ENV VITE_SUPABASE_ENTERPRISE_SSO_ENABLED=${VITE_SUPABASE_ENTERPRISE_SSO_ENABLED}
ENV VITE_SUPABASE_PASSKEYS_ENABLED=${VITE_SUPABASE_PASSKEYS_ENABLED}
ENV VITE_SUPABASE_TOTP_MFA_ENABLED=${VITE_SUPABASE_TOTP_MFA_ENABLED}
ENV VITE_SUPABASE_SMS_MFA_FALLBACK_ENABLED=${VITE_SUPABASE_SMS_MFA_FALLBACK_ENABLED}

RUN npm run build

FROM node:22-bookworm-slim AS runtime

WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8080

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY --from=build /app/dist ./dist
COPY --from=build /app/public ./public
COPY --from=build /app/server.mjs ./server.mjs

EXPOSE 8080

CMD ["npm", "run", "start"]