import type {
  ProductComponentInsert,
  ProductFeatureCardInsert,
  ProductPageInsert,
  ProductPageLayoutInsert,
  ProductProjectInsert,
  ProductUserflowInsert,
  ProductUserflowPageInsert,
} from '../../types/productSchema';

type FlowForgePageSeed = Omit<ProductPageInsert, 'project_id'>;
type FlowForgeComponentSeed = Omit<ProductComponentInsert, 'project_id'>;
type FlowForgeLayoutSeed = Omit<ProductPageLayoutInsert, 'page_id'> & {
  pageSlug: string;
};
type FlowForgeFeatureSeed = Omit<ProductFeatureCardInsert, 'project_id'> & {
  pageSlugs: string[];
  componentSlugs: string[];
  userflowSlugs: string[];
};
type FlowForgeUserflowStepSeed = Omit<ProductUserflowPageInsert, 'userflow_id' | 'page_id'> & {
  pageSlug: string;
};
type FlowForgeUserflowSeed = Omit<ProductUserflowInsert, 'project_id'> & {
  steps: FlowForgeUserflowStepSeed[];
};

export const FLOWFORGE_PROJECT_SLUG = 'flowforge-ai';
export const FLOWFORGE_SYSTEM_OWNER = 'system-flowforge';

export const flowforgeProjectSeed: ProductProjectInsert = {
  name: 'FlowForge AI',
  slug: FLOWFORGE_PROJECT_SLUG,
  description: 'AI-assisted product orchestration workspace that turns app ideas into structured product data, implementation guidance, and portfolio-ready project overviews.',
  tagline: 'Turn app ideas into product architecture, build plans, and reusable project intelligence.',
  category: 'ai-product-platform',
  tags: ['ai', 'product-management', 'app-builder', 'supabase', 'ui-architecture'],
  visibility: 'internal',
  platform: 'responsive',
  status: 'active',
  version: '1.0.0',
  owner_auth_id: FLOWFORGE_SYSTEM_OWNER,
  app_icon_url: null,
  hero_image_url: null,
  demo_url: null,
  source_url: 'https://github.com/MyMindVentures/FlowForge-AI',
  featured_rank: 100,
  last_synced_at: null,
  catalog_metadata: {
    repository: 'MyMindVentures/FlowForge-AI',
    sync_source: 'repo-catalog-seed',
    app_kind: 'self-hosted product orchestration workspace',
  },
};

export const flowforgePageSeeds: FlowForgePageSeed[] = [
  {
    name: 'Splash',
    slug: 'splash',
    page_type: 'screen',
    description: 'Initial branded loading experience.',
    route: '/',
    purpose: 'Bridge launch state into authenticated product flows.',
    auth_required: false,
    status: 'active',
    screen_title: 'Welcome to FlowForge AI',
    empty_state_description: null,
    error_state_description: null,
    loading_state_description: 'Preparing your workspace...',
  },
  {
    name: 'Auth',
    slug: 'auth',
    page_type: 'form',
    description: 'Authentication entry point for email, Google, and one-time access flows.',
    route: '/auth',
    purpose: 'Authenticate and recover access before onboarding.',
    auth_required: false,
    status: 'active',
    screen_title: 'Sign in',
    empty_state_description: null,
    error_state_description: 'Authentication providers are unavailable or misconfigured.',
    loading_state_description: null,
  },
  {
    name: 'Storytelling',
    slug: 'storytelling',
    page_type: 'screen',
    description: 'Mission-driven onboarding narrative.',
    route: '/storytelling',
    purpose: 'Align founders and builders before project setup.',
    auth_required: false,
    status: 'active',
    screen_title: 'Why FlowForge AI exists',
    empty_state_description: null,
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'Onboarding',
    slug: 'onboarding',
    page_type: 'form',
    description: 'Initial account and app setup flow.',
    route: '/onboarding',
    purpose: 'Collect initial preferences and progress users into role selection.',
    auth_required: false,
    status: 'active',
    screen_title: 'Set up your workspace',
    empty_state_description: null,
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'RoleSelection',
    slug: 'role-selection',
    page_type: 'screen',
    description: 'Role chooser for Architect, Builder, and Admin.',
    route: '/role-selection',
    purpose: 'Tailor the workspace to the user role.',
    auth_required: false,
    status: 'active',
    screen_title: 'Choose your role',
    empty_state_description: null,
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'Dashboard',
    slug: 'dashboard',
    page_type: 'screen',
    description: 'Project portfolio overview and entry point.',
    route: '/projects',
    purpose: 'Browse, create, duplicate, archive, and select projects.',
    auth_required: true,
    status: 'active',
    screen_title: 'Projects',
    empty_state_description: 'No projects exist yet.',
    error_state_description: 'Projects could not be loaded.',
    loading_state_description: 'Loading your projects...',
  },
  {
    name: 'ProjectHub',
    slug: 'project-hub',
    page_type: 'screen',
    description: 'Main workspace hub for a selected project.',
    route: '/projects/:projectId/workspace',
    purpose: 'Provide fast navigation into all core project modules.',
    auth_required: true,
    status: 'active',
    screen_title: 'Workspace',
    empty_state_description: null,
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'FeatureChat',
    slug: 'feature-chat',
    page_type: 'screen',
    description: 'AI-powered ideation and guided feature discovery.',
    route: '/projects/:projectId/ideation',
    purpose: 'Turn raw product ideas into structured feature proposals.',
    auth_required: true,
    status: 'active',
    screen_title: 'Feature ideation',
    empty_state_description: null,
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'Backlog',
    slug: 'backlog',
    page_type: 'list',
    description: 'Feature backlog with search, status, and prioritization.',
    route: '/projects/:projectId/backlog',
    purpose: 'Manage and sequence feature work.',
    auth_required: true,
    status: 'active',
    screen_title: 'Backlog',
    empty_state_description: 'No features have been created yet.',
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'FeatureDetail',
    slug: 'feature-detail',
    page_type: 'detail',
    description: 'Multi-tab feature workflow spanning concept to execution.',
    route: '/projects/:projectId/feature/:featureId',
    purpose: 'Edit feature strategy, prompts, visuals, discussion, and UI impact.',
    auth_required: true,
    status: 'active',
    screen_title: 'Feature detail',
    empty_state_description: null,
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'Roadmap',
    slug: 'roadmap',
    page_type: 'screen',
    description: 'Release roadmap and version planning surface.',
    route: '/projects/:projectId/roadmap',
    purpose: 'Link features to releases and milestones.',
    auth_required: true,
    status: 'active',
    screen_title: 'Roadmap',
    empty_state_description: 'No releases have been planned yet.',
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'ProjectKnowledgeBase',
    slug: 'project-knowledge-base',
    page_type: 'screen',
    description: 'Project-wide documentation and shared context.',
    route: '/projects/:projectId/knowledge-base',
    purpose: 'Centralize app vision, specs, and reusable knowledge.',
    auth_required: true,
    status: 'active',
    screen_title: 'Knowledge base',
    empty_state_description: null,
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'MarketingKit',
    slug: 'marketing-kit',
    page_type: 'screen',
    description: 'AI-assisted positioning and messaging generator.',
    route: '/projects/:projectId/marketing',
    purpose: 'Generate project-level marketing assets from product data.',
    auth_required: true,
    status: 'active',
    screen_title: 'Marketing kit',
    empty_state_description: null,
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'AssetManager',
    slug: 'asset-manager',
    page_type: 'screen',
    description: 'Project asset storage and feature linking.',
    route: '/projects/:projectId/assets',
    purpose: 'Manage uploaded images, logos, and documents.',
    auth_required: true,
    status: 'active',
    screen_title: 'Assets',
    empty_state_description: 'No assets uploaded yet.',
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'ProjectSettings',
    slug: 'project-settings',
    page_type: 'settings',
    description: 'Project metadata, vision, architecture, and UX strategy editor.',
    route: '/projects/:projectId/settings',
    purpose: 'Maintain project-level configuration and context.',
    auth_required: true,
    status: 'active',
    screen_title: 'Project settings',
    empty_state_description: null,
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'UIArchitecture',
    slug: 'ui-architecture',
    page_type: 'screen',
    description: 'Visual information architecture for pages, components, and layouts.',
    route: '/projects/:projectId/ui-architecture',
    purpose: 'Model app screens and reusable components before buildout.',
    auth_required: true,
    status: 'active',
    screen_title: 'UI architecture',
    empty_state_description: 'No pages or components defined yet.',
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'Notifications',
    slug: 'notifications',
    page_type: 'screen',
    description: 'Notifications center for system and project activity.',
    route: '/notifications',
    purpose: 'Surface user-relevant updates across the app.',
    auth_required: true,
    status: 'draft',
    screen_title: 'Notifications',
    empty_state_description: 'Notifications are not implemented yet.',
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'AIAgents',
    slug: 'ai-agents',
    page_type: 'screen',
    description: 'Project-level AI agent overview and configuration.',
    route: '/agents',
    purpose: 'Inspect and configure agent capabilities and model usage.',
    auth_required: true,
    status: 'active',
    screen_title: 'AI agents',
    empty_state_description: null,
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'Admin',
    slug: 'admin',
    page_type: 'screen',
    description: 'Admin control center for audits, PRDs, and sync operations.',
    route: '/admin',
    purpose: 'Operate platform-wide controls and diagnostics.',
    auth_required: true,
    status: 'active',
    screen_title: 'Admin',
    empty_state_description: null,
    error_state_description: null,
    loading_state_description: null,
  },
  {
    name: 'Workspace',
    slug: 'workspace',
    page_type: 'screen',
    description: 'Legacy workspace shell retained as a route target and test surface.',
    route: '/projects/:projectId/workspace-shell',
    purpose: 'Preserve workspace-level collaboration functionality alongside ProjectHub.',
    auth_required: true,
    status: 'active',
    screen_title: 'Workspace shell',
    empty_state_description: null,
    error_state_description: null,
    loading_state_description: null,
  },
];

export const flowforgeLayoutSeeds: FlowForgeLayoutSeed[] = flowforgePageSeeds.map((page) => ({
  pageSlug: page.slug,
  name: `${page.name} Primary Layout`,
  layout_type: page.page_type === 'modal' ? 'modal' : page.auth_required ? 'default' : 'mobile',
  description: `Primary layout for ${page.name}.`,
  breakpoint: null,
  grid_definition: {},
  notes: null,
  version: '1.0.0',
  is_primary: true,
}));

export const flowforgeComponentSeeds: FlowForgeComponentSeed[] = [
  {
    name: 'Layout',
    slug: 'layout',
    component_type: 'layout',
    description: 'Global application shell with navigation and sync context.',
    design_purpose: 'Wrap authenticated app routes.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'global',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/Layout.tsx',
    status: 'active',
  },
  {
    name: 'SyncIndicator',
    slug: 'sync-indicator',
    component_type: 'status',
    description: 'Visual sync-state badge.',
    design_purpose: 'Show synchronization health in the global shell.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'shared',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/SyncIndicator.tsx',
    status: 'active',
  },
  {
    name: 'IntegrityBadge',
    slug: 'integrity-badge',
    component_type: 'status',
    description: 'Integrity state chip for verified, incomplete, and out-of-sync entities.',
    design_purpose: 'Expose truth-state across product entities.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'shared',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/IntegrityBadge.tsx',
    status: 'active',
  },
  {
    name: 'ConfirmModal',
    slug: 'confirm-modal',
    component_type: 'modal',
    description: 'Confirmation dialog for destructive actions.',
    design_purpose: 'Protect project deletion and irreversible actions.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'shared',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/ConfirmModal.tsx',
    status: 'active',
  },
  {
    name: 'Toast',
    slug: 'toast',
    component_type: 'feedback',
    description: 'Transient toast notifications.',
    design_purpose: 'Report action success and failure across the app.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'global',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/Toast.tsx',
    status: 'active',
  },
  {
    name: 'ErrorBoundary',
    slug: 'error-boundary',
    component_type: 'feedback',
    description: 'Global UI fallback for runtime failures.',
    design_purpose: 'Keep the app recoverable on render failures.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'global',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/ErrorBoundary.tsx',
    status: 'active',
  },
  {
    name: 'FeatureOverview',
    slug: 'feature-overview',
    component_type: 'section',
    description: 'Feature metadata and executive overview.',
    design_purpose: 'Anchor the feature detail workflow.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'feature',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/feature/FeatureOverview.tsx',
    status: 'active',
  },
  {
    name: 'FeatureConcept',
    slug: 'feature-concept',
    component_type: 'section',
    description: 'Concept framing and generated idea articulation.',
    design_purpose: 'Translate raw ideas into a product concept.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'feature',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/feature/FeatureConcept.tsx',
    status: 'active',
  },
  {
    name: 'FeatureBuilderBrief',
    slug: 'feature-builder-brief',
    component_type: 'section',
    description: 'Implementation-oriented brief for builders.',
    design_purpose: 'Hand off product intent into technical work.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'feature',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/feature/FeatureBuilderBrief.tsx',
    status: 'active',
  },
  {
    name: 'FeaturePrompts',
    slug: 'feature-prompts',
    component_type: 'section',
    description: 'Prompt packs for coding and design execution.',
    design_purpose: 'Package AI instructions for downstream work.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'feature',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/feature/FeaturePrompts.tsx',
    status: 'active',
  },
  {
    name: 'FeatureDiscussion',
    slug: 'feature-discussion',
    component_type: 'section',
    description: 'Discussion thread for feature collaboration.',
    design_purpose: 'Keep architect and builder context attached to a feature.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'feature',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/feature/FeatureDiscussion.tsx',
    status: 'active',
  },
  {
    name: 'FeatureAudit',
    slug: 'feature-audit',
    component_type: 'section',
    description: 'Feature audit log and integrity summary.',
    design_purpose: 'Track feature history and quality checks.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'feature',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/feature/FeatureAudit.tsx',
    status: 'active',
  },
  {
    name: 'FeatureVisuals',
    slug: 'feature-visuals',
    component_type: 'section',
    description: 'AI-generated feature visuals.',
    design_purpose: 'Visualize a feature concept and supporting assets.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'feature',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/feature/FeatureVisuals.tsx',
    status: 'active',
  },
  {
    name: 'FeatureUIArchitecture',
    slug: 'feature-ui-architecture',
    component_type: 'section',
    description: 'Feature-scoped page and component mapping.',
    design_purpose: 'Link features to UI architecture entities.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'feature',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/feature/FeatureUIArchitecture.tsx',
    status: 'active',
  },
  {
    name: 'PageModal',
    slug: 'page-modal',
    component_type: 'modal',
    description: 'Page editor modal.',
    design_purpose: 'Create and edit page records inside the UI architecture tool.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'architecture',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/ui-architecture/PageModal.tsx',
    status: 'active',
  },
  {
    name: 'ComponentModal',
    slug: 'component-modal',
    component_type: 'modal',
    description: 'Component editor modal.',
    design_purpose: 'Create and edit reusable component records.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'architecture',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/ui-architecture/ComponentModal.tsx',
    status: 'active',
  },
  {
    name: 'LayoutModal',
    slug: 'layout-modal',
    component_type: 'modal',
    description: 'Layout editor modal.',
    design_purpose: 'Edit per-page layout metadata.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'architecture',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/ui-architecture/LayoutModal.tsx',
    status: 'active',
  },
  {
    name: 'StyleModal',
    slug: 'style-modal',
    component_type: 'modal',
    description: 'Design system settings modal.',
    design_purpose: 'Manage colors, typography, spacing, and surface tokens.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'architecture',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/ui-architecture/StyleModal.tsx',
    status: 'active',
  },
  {
    name: 'PageVisualGrid',
    slug: 'page-visual-grid',
    component_type: 'section',
    description: 'Gallery of generated page visuals.',
    design_purpose: 'Preview generated page concepts.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'architecture',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/ui-architecture/PageVisualGrid.tsx',
    status: 'active',
  },
  {
    name: 'PageDetailView',
    slug: 'page-detail-view',
    component_type: 'section',
    description: 'Detailed page viewer.',
    design_purpose: 'Inspect page metadata and linked entities.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'architecture',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/ui-architecture/PageDetailView.tsx',
    status: 'active',
  },
  {
    name: 'LLMFunctionsManagement',
    slug: 'llm-functions-management',
    component_type: 'section',
    description: 'Admin editor for project and global LLM functions.',
    design_purpose: 'Configure AI function routing and overrides.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'admin',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/LLMFunctionsManagement.tsx',
    status: 'active',
  },
  {
    name: 'FullPRD',
    slug: 'full-prd',
    component_type: 'section',
    description: 'Full product requirements document viewer.',
    design_purpose: 'Review a consolidated PRD in the admin area.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'admin',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/admin/FullPRD.tsx',
    status: 'active',
  },
  {
    name: 'Tasklist',
    slug: 'tasklist',
    component_type: 'section',
    description: 'Task and sync board for implementation tracking.',
    design_purpose: 'Monitor system tasks and sync outputs.',
    props_schema: {},
    states: [],
    variants: [],
    reusability_level: 'admin',
    design_system_ref: null,
    figma_link: null,
    dev_reference: 'src/components/admin/Tasklist.tsx',
    status: 'active',
  },
];

export const flowforgeUserflowSeeds: FlowForgeUserflowSeed[] = [
  {
    name: 'Founder Onboarding',
    slug: 'founder-onboarding',
    description: 'Guide a new user from launch through role selection into project browsing.',
    goal: 'Establish mission context and workspace intent before product work starts.',
    entry_point: '/',
    exit_point: '/projects',
    primary_actor: 'Founder',
    status: 'active',
    version: '1.0.0',
    steps: [
      { pageSlug: 'splash', step_order: 1, step_name: 'Launch app', is_optional: false, condition: null, notes: null },
      { pageSlug: 'auth', step_order: 2, step_name: 'Authenticate', is_optional: false, condition: null, notes: null },
      { pageSlug: 'storytelling', step_order: 3, step_name: 'Absorb narrative', is_optional: false, condition: null, notes: null },
      { pageSlug: 'onboarding', step_order: 4, step_name: 'Complete setup', is_optional: false, condition: null, notes: null },
      { pageSlug: 'role-selection', step_order: 5, step_name: 'Choose role', is_optional: false, condition: null, notes: null },
      { pageSlug: 'dashboard', step_order: 6, step_name: 'Enter projects', is_optional: false, condition: null, notes: null },
    ],
  },
  {
    name: 'Project Planning',
    slug: 'project-planning',
    description: 'Navigate a selected project from hub into core planning surfaces.',
    goal: 'Create a coherent project plan and supporting knowledge assets.',
    entry_point: '/projects',
    exit_point: '/projects/:projectId/ui-architecture',
    primary_actor: 'Architect',
    status: 'active',
    version: '1.0.0',
    steps: [
      { pageSlug: 'dashboard', step_order: 1, step_name: 'Select project', is_optional: false, condition: null, notes: null },
      { pageSlug: 'project-hub', step_order: 2, step_name: 'Open workspace hub', is_optional: false, condition: null, notes: null },
      { pageSlug: 'project-knowledge-base', step_order: 3, step_name: 'Refine knowledge base', is_optional: true, condition: null, notes: null },
      { pageSlug: 'project-settings', step_order: 4, step_name: 'Adjust project settings', is_optional: true, condition: null, notes: null },
      { pageSlug: 'ui-architecture', step_order: 5, step_name: 'Plan the UI architecture', is_optional: false, condition: null, notes: null },
    ],
  },
  {
    name: 'Feature Delivery',
    slug: 'feature-delivery',
    description: 'Transform an idea into a structured, build-ready feature.',
    goal: 'Move from ideation to a detailed feature implementation plan.',
    entry_point: '/projects/:projectId/ideation',
    exit_point: '/projects/:projectId/feature/:featureId',
    primary_actor: 'Architect and Builder',
    status: 'active',
    version: '1.0.0',
    steps: [
      { pageSlug: 'feature-chat', step_order: 1, step_name: 'Generate feature ideas', is_optional: false, condition: null, notes: null },
      { pageSlug: 'backlog', step_order: 2, step_name: 'Review backlog', is_optional: false, condition: null, notes: null },
      { pageSlug: 'feature-detail', step_order: 3, step_name: 'Develop feature detail', is_optional: false, condition: null, notes: null },
      { pageSlug: 'roadmap', step_order: 4, step_name: 'Place into roadmap', is_optional: true, condition: null, notes: null },
    ],
  },
  {
    name: 'Admin Operations',
    slug: 'admin-operations',
    description: 'Operate platform settings, tasks, and AI routing.',
    goal: 'Maintain platform health, audits, and AI configuration.',
    entry_point: '/admin',
    exit_point: '/agents',
    primary_actor: 'Admin',
    status: 'active',
    version: '1.0.0',
    steps: [
      { pageSlug: 'admin', step_order: 1, step_name: 'Open admin', is_optional: false, condition: null, notes: null },
      { pageSlug: 'dashboard', step_order: 2, step_name: 'Inspect project portfolio', is_optional: true, condition: null, notes: null },
      { pageSlug: 'ai-agents', step_order: 3, step_name: 'Review AI agents', is_optional: false, condition: null, notes: null },
      { pageSlug: 'notifications', step_order: 4, step_name: 'Check notifications', is_optional: true, condition: 'Feature remains partial.', notes: null },
    ],
  },
];

export const flowforgeFeatureSeeds: FlowForgeFeatureSeed[] = [
  {
    title: 'Authentication and Onboarding',
    slug: 'authentication-and-onboarding',
    summary: 'Authentication, narrative onboarding, and role selection establish the user context.',
    problem_statement: 'Founders and builders need guided entry into the workspace with correct access and shared context.',
    goal: 'Authenticate users and move them into the right product workflow.',
    user_value: 'Users can securely enter the app and understand its purpose before starting work.',
    business_value: 'Improves activation quality and preserves role-based control.',
    priority: 'critical',
    status: 'done',
    category: 'core',
    epic: 'foundation',
    release: '1.0.0',
    persona: 'Founder, Builder, Admin',
    jobs_to_be_done: 'Help me access the workspace and understand how FlowForge AI supports my role.',
    acceptance_criteria: 'Splash, auth, storytelling, onboarding, and role selection flows all exist and route correctly.',
    success_metrics: 'Authenticated users complete onboarding and reach the dashboard.',
    non_functional_requirements: 'Auth errors should be surfaced clearly and access should be role-aware.',
    dependencies: 'Supabase auth and the current project profile bootstrap flow.',
    assumptions: 'Users complete narrative onboarding before selecting a role.',
    risks: 'Provider misconfiguration blocks access.',
    notes: 'Includes email, Google, magic link, and one-time code pathways in the current app.',
    figma_link: null,
    spec_link: null,
    owner_auth_id: FLOWFORGE_SYSTEM_OWNER,
    pageSlugs: ['splash', 'auth', 'storytelling', 'onboarding', 'role-selection'],
    componentSlugs: ['layout', 'toast', 'error-boundary'],
    userflowSlugs: ['founder-onboarding'],
  },
  {
    title: 'Project Portfolio Dashboard',
    slug: 'project-portfolio-dashboard',
    summary: 'The dashboard manages project overview cards and creation flows.',
    problem_statement: 'Users need a portfolio-level surface to browse and select projects quickly.',
    goal: 'Provide a searchable and filterable overview of all app projects.',
    user_value: 'Users can create, duplicate, archive, and reopen projects from one place.',
    business_value: 'This is the main entry point for supporting many app projects in one database.',
    priority: 'critical',
    status: 'done',
    category: 'portfolio',
    epic: 'project-management',
    release: '1.0.0',
    persona: 'Architect, Admin',
    jobs_to_be_done: 'Help me find or create the right project quickly.',
    acceptance_criteria: 'Project list supports filtering, search, create, archive, duplicate, and delete.',
    success_metrics: 'Projects render as overview cards with metadata and fresh activity.',
    non_functional_requirements: 'Project queries should scale for many app projects.',
    dependencies: 'Project repository queries and overview catalog metadata.',
    assumptions: 'The dashboard becomes Supabase-backed for overview rendering.',
    risks: 'Current implementation still mixes legacy collection-style reads with newer repository queries.',
    notes: 'This is the primary consumer for future multi-project overview queries.',
    figma_link: null,
    spec_link: null,
    owner_auth_id: FLOWFORGE_SYSTEM_OWNER,
    pageSlugs: ['dashboard', 'project-hub', 'project-settings'],
    componentSlugs: ['confirm-modal', 'toast', 'integrity-badge'],
    userflowSlugs: ['project-planning', 'admin-operations'],
  },
  {
    title: 'Project Hub and Workspace',
    slug: 'project-hub-and-workspace',
    summary: 'A central hub routes a selected project into all major modules.',
    problem_statement: 'Without a strong workspace shell, product planning becomes fragmented across many screens.',
    goal: 'Provide a coherent navigation model per project.',
    user_value: 'Users move from a project overview into feature, roadmap, marketing, and architecture work without losing context.',
    business_value: 'Keeps project-level workflows organized as the app portfolio grows.',
    priority: 'high',
    status: 'done',
    category: 'workspace',
    epic: 'project-management',
    release: '1.0.0',
    persona: 'Architect, Builder',
    jobs_to_be_done: 'Help me navigate a project and keep its context attached to every module.',
    acceptance_criteria: 'ProjectHub and workspace routes expose all linked modules.',
    success_metrics: 'Users can enter a project and navigate directly to target workflows.',
    non_functional_requirements: 'Project context must remain stable across route changes.',
    dependencies: 'Project context provider and global layout.',
    assumptions: 'Each selected project has a consistent route namespace.',
    risks: 'Context drift while legacy collection abstractions and newer repository queries coexist.',
    notes: 'ProjectHub acts as the main module launcher for a selected project.',
    figma_link: null,
    spec_link: null,
    owner_auth_id: FLOWFORGE_SYSTEM_OWNER,
    pageSlugs: ['project-hub', 'workspace'],
    componentSlugs: ['layout', 'sync-indicator'],
    userflowSlugs: ['project-planning'],
  },
  {
    title: 'AI Feature Ideation',
    slug: 'ai-feature-ideation',
    summary: 'AI chat turns high-level product intent into candidate features.',
    problem_statement: 'Founders need structured help turning fuzzy ideas into backlog-ready work.',
    goal: 'Generate, refine, and capture promising features.',
    user_value: 'Users can brainstorm with AI and quickly convert outputs into the backlog.',
    business_value: 'Accelerates product discovery and strengthens FlowForge AI’s core proposition.',
    priority: 'critical',
    status: 'done',
    category: 'ai',
    epic: 'feature-management',
    release: '1.0.0',
    persona: 'Architect',
    jobs_to_be_done: 'Help me turn an idea into a structured feature proposal.',
    acceptance_criteria: 'Feature chat and backlog flow are integrated.',
    success_metrics: 'Users create actionable features from ideation sessions.',
    non_functional_requirements: 'AI responses should be resilient and informative on failure.',
    dependencies: 'Gemini services and project context.',
    assumptions: 'Generated suggestions are reviewed before adoption.',
    risks: 'Weak prompts reduce feature quality.',
    notes: 'FeatureChat is the front door into the feature workflow.',
    figma_link: null,
    spec_link: null,
    owner_auth_id: FLOWFORGE_SYSTEM_OWNER,
    pageSlugs: ['feature-chat', 'backlog'],
    componentSlugs: ['toast'],
    userflowSlugs: ['feature-delivery'],
  },
  {
    title: 'Structured Feature Delivery Workflow',
    slug: 'structured-feature-delivery-workflow',
    summary: 'The feature detail surface organizes concept, brief, prompts, discussion, audit, visuals, and UI impact.',
    problem_statement: 'Teams need more than a backlog item to move work into implementation.',
    goal: 'Provide a detailed, role-aware feature workspace.',
    user_value: 'Users can carry a feature from concept to build-ready context in one place.',
    business_value: 'Differentiates FlowForge AI from a simple backlog tool.',
    priority: 'critical',
    status: 'done',
    category: 'workflow',
    epic: 'feature-management',
    release: '1.0.0',
    persona: 'Architect, Builder',
    jobs_to_be_done: 'Help me fully specify a feature before implementation starts.',
    acceptance_criteria: 'All feature detail tabs exist and persist state.',
    success_metrics: 'Features accumulate structured context across tabs.',
    non_functional_requirements: 'Feature updates should be auditable and recoverable.',
    dependencies: 'Feature store, audit service, AI services, UI architecture entities.',
    assumptions: 'Feature detail is the central delivery artifact.',
    risks: 'Some audit/UI architecture subflows are still partial.',
    notes: 'Covers overview, concept, builder brief, prompts, discussion, audit, visuals, and UI architecture.',
    figma_link: null,
    spec_link: null,
    owner_auth_id: FLOWFORGE_SYSTEM_OWNER,
    pageSlugs: ['feature-detail', 'backlog'],
    componentSlugs: ['feature-overview', 'feature-concept', 'feature-builder-brief', 'feature-prompts', 'feature-discussion', 'feature-audit', 'feature-visuals', 'feature-ui-architecture'],
    userflowSlugs: ['feature-delivery'],
  },
  {
    title: 'UI Architecture Planner',
    slug: 'ui-architecture-planner',
    summary: 'FlowForge AI models pages, components, layouts, style tokens, and generated visuals.',
    problem_statement: 'Non-designers need a structured way to define interface architecture before code.',
    goal: 'Capture a usable UI architecture inside the product model.',
    user_value: 'Users can define screens, reusable components, layouts, and design-system metadata in one workspace.',
    business_value: 'Creates durable product data that can power downstream code and overview generation.',
    priority: 'high',
    status: 'done',
    category: 'architecture',
    epic: 'product-model',
    release: '1.0.0',
    persona: 'Architect, Builder',
    jobs_to_be_done: 'Help me plan the structure of an app visually and systematically.',
    acceptance_criteria: 'Pages, components, layouts, style settings, and visual previews can be managed.',
    success_metrics: 'Projects store reusable architecture entities that can be queried and linked to features.',
    non_functional_requirements: 'Architecture entities should normalize well in the database.',
    dependencies: 'Pages, components, page layouts, and relation tables.',
    assumptions: 'Design system preview remains basic in the current UI.',
    risks: 'Integration between layout and page detail remains incomplete.',
    notes: 'Includes AI-generated UI architecture and supporting editor modals.',
    figma_link: null,
    spec_link: null,
    owner_auth_id: FLOWFORGE_SYSTEM_OWNER,
    pageSlugs: ['ui-architecture'],
    componentSlugs: ['page-modal', 'component-modal', 'layout-modal', 'style-modal', 'page-visual-grid', 'page-detail-view'],
    userflowSlugs: ['project-planning'],
  },
  {
    title: 'Roadmap and Release Planning',
    slug: 'roadmap-and-release-planning',
    summary: 'The roadmap organizes versions and release sequencing.',
    problem_statement: 'Teams need to organize features into releases and milestones.',
    goal: 'Visualize releases and attach features to versions.',
    user_value: 'Users can move from feature creation into planning and release management.',
    business_value: 'Improves delivery planning and project overview completeness.',
    priority: 'medium',
    status: 'done',
    category: 'planning',
    epic: 'project-management',
    release: '1.0.0',
    persona: 'Architect',
    jobs_to_be_done: 'Help me organize features into coherent releases.',
    acceptance_criteria: 'Users can create and manage roadmap entries.',
    success_metrics: 'Projects accumulate version and release context.',
    non_functional_requirements: 'Roadmap state should remain queryable and sortable.',
    dependencies: 'Version data and feature relationships.',
    assumptions: 'Current release planning remains relatively lightweight.',
    risks: 'No dedicated release table exists yet in the new product model.',
    notes: 'Future versions table can enrich this further.',
    figma_link: null,
    spec_link: null,
    owner_auth_id: FLOWFORGE_SYSTEM_OWNER,
    pageSlugs: ['roadmap'],
    componentSlugs: [],
    userflowSlugs: ['feature-delivery'],
  },
  {
    title: 'Project Knowledge Base',
    slug: 'project-knowledge-base',
    summary: 'A central documentation space keeps project-specific knowledge close to execution.',
    problem_statement: 'Important product context gets lost when it is spread across chats and documents.',
    goal: 'Preserve project vision, specs, and reusable guidance.',
    user_value: 'Users can store shared context once and reuse it across AI-assisted workflows.',
    business_value: 'Improves output quality and reduces repeated prompting.',
    priority: 'high',
    status: 'done',
    category: 'documentation',
    epic: 'project-management',
    release: '1.0.0',
    persona: 'Architect, Builder',
    jobs_to_be_done: 'Help me keep all project knowledge accessible in the workspace.',
    acceptance_criteria: 'Knowledge base page exists and updates project-level data.',
    success_metrics: 'Projects keep reusable context attached to their product record.',
    non_functional_requirements: 'Knowledge updates should persist reliably.',
    dependencies: 'Project settings and feature data.',
    assumptions: 'Knowledge base complements, not replaces, PRD generation.',
    risks: 'Schema support for richer docs remains incomplete in the product model.',
    notes: 'This is a core differentiator for future project overviews.',
    figma_link: null,
    spec_link: null,
    owner_auth_id: FLOWFORGE_SYSTEM_OWNER,
    pageSlugs: ['project-knowledge-base', 'project-settings'],
    componentSlugs: [],
    userflowSlugs: ['project-planning'],
  },
  {
    title: 'Asset Management',
    slug: 'asset-management',
    summary: 'Projects can store and associate assets with features.',
    problem_statement: 'Product teams need visual and document assets tied to project work.',
    goal: 'Maintain a project asset library with feature linkage.',
    user_value: 'Users can upload and organize images, logos, and documents.',
    business_value: 'Supports marketing, design, and implementation workflows.',
    priority: 'medium',
    status: 'done',
    category: 'assets',
    epic: 'project-management',
    release: '1.0.0',
    persona: 'Architect, Builder',
    jobs_to_be_done: 'Help me keep a project’s assets in one place.',
    acceptance_criteria: 'Asset manager supports uploads and feature linking.',
    success_metrics: 'Assets are attached to the right projects and features.',
    non_functional_requirements: 'Uploads should respect size limits and metadata constraints.',
    dependencies: 'Project and feature entities.',
    assumptions: 'Asset storage backend remains compatible with current implementation.',
    risks: 'Binary storage and DB metadata may still be split across systems.',
    notes: 'Current UI validates and categorizes uploads.',
    figma_link: null,
    spec_link: null,
    owner_auth_id: FLOWFORGE_SYSTEM_OWNER,
    pageSlugs: ['asset-manager'],
    componentSlugs: [],
    userflowSlugs: ['project-planning'],
  },
  {
    title: 'Marketing Kit Generation',
    slug: 'marketing-kit-generation',
    summary: 'AI-generated messaging turns product data into external positioning.',
    problem_statement: 'Founders need help articulating value propositions and marketing copy.',
    goal: 'Generate project-aware positioning and messaging.',
    user_value: 'Users can quickly produce taglines, value props, and messaging from project data.',
    business_value: 'Expands FlowForge AI from planning into launch-support workflows.',
    priority: 'medium',
    status: 'done',
    category: 'marketing',
    epic: 'go-to-market',
    release: '1.0.0',
    persona: 'Founder',
    jobs_to_be_done: 'Help me package my project into clear messaging.',
    acceptance_criteria: 'Marketing kit page generates usable outputs from project context.',
    success_metrics: 'Users can create marketing collateral without leaving the product workspace.',
    non_functional_requirements: 'Outputs should be fast and resilient to model failures.',
    dependencies: 'Feature and project context plus AI services.',
    assumptions: 'Marketing outputs are review drafts, not final truth.',
    risks: 'Weak project context reduces output quality.',
    notes: 'Pairs naturally with the knowledge base and feature backlog.',
    figma_link: null,
    spec_link: null,
    owner_auth_id: FLOWFORGE_SYSTEM_OWNER,
    pageSlugs: ['marketing-kit'],
    componentSlugs: [],
    userflowSlugs: ['project-planning'],
  },
  {
    title: 'AI Agents and LLM Function Management',
    slug: 'ai-agents-and-llm-function-management',
    summary: 'Admins and project owners can inspect agent capabilities and override function behavior.',
    problem_statement: 'As AI usage grows, projects need explicit control over routing and function behavior.',
    goal: 'Provide an operational surface for AI agents and LLM functions.',
    user_value: 'Users can understand and adjust AI capabilities at project or system level.',
    business_value: 'Improves maintainability, experimentation, and operational trust.',
    priority: 'high',
    status: 'done',
    category: 'admin',
    epic: 'ai-ops',
    release: '1.0.0',
    persona: 'Admin',
    jobs_to_be_done: 'Help me control how AI functions behave for this platform and its projects.',
    acceptance_criteria: 'Agent hub and LLM function management surface are both available.',
    success_metrics: 'AI configuration becomes discoverable and overrideable.',
    non_functional_requirements: 'Configuration changes must remain safe and auditable.',
    dependencies: 'AI models, prompts, and function configuration data.',
    assumptions: 'Fallback routing remains an area for future improvement.',
    risks: 'Incomplete fallback logic can limit resilience.',
    notes: 'Connects the admin area with project-level AI configuration.',
    figma_link: null,
    spec_link: null,
    owner_auth_id: FLOWFORGE_SYSTEM_OWNER,
    pageSlugs: ['ai-agents', 'admin'],
    componentSlugs: ['llm-functions-management', 'full-prd', 'tasklist'],
    userflowSlugs: ['admin-operations'],
  },
  {
    title: 'Audit and Sync Integrity',
    slug: 'audit-and-sync-integrity',
    summary: 'The platform tracks integrity state and supports code-to-data synchronization workflows.',
    problem_statement: 'Product data loses value if it drifts from the implementation reality.',
    goal: 'Keep FlowForge AI as a reliable reference project synchronized with its codebase.',
    user_value: 'Users can trust the project model and inspect drift or audit signals.',
    business_value: 'Creates a foundation for portfolio-wide project overview correctness.',
    priority: 'critical',
    status: 'planned',
    category: 'sync',
    epic: 'platform-integrity',
    release: '1.0.0',
    persona: 'Admin',
    jobs_to_be_done: 'Help me keep the project database aligned with the real application.',
    acceptance_criteria: 'Sync and audit pathways can update the canonical project inventory.',
    success_metrics: 'Project overviews remain current and drift is visible.',
    non_functional_requirements: 'Sync runs must be idempotent and safe.',
    dependencies: 'Supabase sync command, audit data, integrity indicators.',
    assumptions: 'This new sync script becomes the canonical backfill entry point.',
    risks: 'Legacy collection-oriented sync paths can remain stale until fully migrated.',
    notes: 'This implementation pass starts the Supabase-backed sync foundation.',
    figma_link: null,
    spec_link: null,
    owner_auth_id: FLOWFORGE_SYSTEM_OWNER,
    pageSlugs: ['admin', 'dashboard'],
    componentSlugs: ['sync-indicator', 'integrity-badge', 'tasklist'],
    userflowSlugs: ['admin-operations'],
  },
  {
    title: 'Notifications Center',
    slug: 'notifications-center',
    summary: 'A placeholder for system and project notifications.',
    problem_statement: 'Users will need cross-project awareness as the portfolio grows.',
    goal: 'Create a future notifications layer spanning multiple app projects.',
    user_value: 'Users will be able to see relevant updates without visiting each module manually.',
    business_value: 'Supports multi-project coordination and portfolio operations.',
    priority: 'medium',
    status: 'backlog',
    category: 'communication',
    epic: 'platform-foundation',
    release: '1.0.0',
    persona: 'Architect, Builder, Admin',
    jobs_to_be_done: 'Help me see what changed across my projects.',
    acceptance_criteria: 'Notifications page becomes fully implemented.',
    success_metrics: 'Cross-project alerts and workflow signals become visible.',
    non_functional_requirements: 'Notifications should scale across many projects and users.',
    dependencies: 'Notification persistence and event generation.',
    assumptions: 'Current page remains a placeholder.',
    risks: 'Schema and UX requirements are still open.',
    notes: 'Deliberately marked as backlog to distinguish from implemented features.',
    figma_link: null,
    spec_link: null,
    owner_auth_id: FLOWFORGE_SYSTEM_OWNER,
    pageSlugs: ['notifications'],
    componentSlugs: [],
    userflowSlugs: ['admin-operations'],
  },
];

